config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'instances/index'
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks", confirmations: "confirmations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  authenticated :user do
    root "missions#dashboard"
  end

  root 'public#landing'
  get 'story', :to => 'public#story'
  resources :announcements, only: [:show]
  resources :notifications do
    collection do
      post :mark_as_checked_all
      post :mark_as_read_all
    end
    member do
      post :mark_as_read
    end
  end
  resources :invitations, only: [:index, :show] do
    member do
      post :accept
      post :decline
      post :cancel
      post :read_all_msg
    end
    collection do
      get :sent_index
    end
    resources :invite_msgs, only: [:create]
  end
  resources :invite_msgs, only: [:show]
  resources :instances, only: [:show, :edit] do
    member do
      post :submit
      patch :submit  #任務完成，提交答案
      post :save
      post :cancel   #取消組隊
      post :abort    #放棄任務
    end

    collection do
      get :history
    end
    resources :instance_msgs, only: [:create]
  end

  resources :followships, only: [:create, :destroy]

  resources :missions, only: [:index, :show] do
    member do
      get :dashboard
      post :challenge
      get :select_user
      # POST challenge_mission_path 挑戰本任務
    end

    collection do
      get :teaming
    end
  end

  resources :reviews, only: [:index, :show] do
    member do
      patch :submit
    end
  end

  resources :users do
    member do
      post :invite
      get :repos
    end
  end

  namespace :admin do
    root "missions#index"
    resources :missions
    resources :instances, only: [:index]
    resources :announcements
  end

  resources :recruit_boards, only: [:index, :create, :destroy] do
    member do
      post :accept
    end
  end

  mount ActionCable.server => '/cable'

end

app/models/instance.rb
class Instance < ApplicationRecord
  after_commit :setup_state!
  after_commit :create_notifications
  has_many :user_instances, dependent: :destroy

  #instance.members 表示此副本的所有成員
  has_many :members, through: :user_instances, source: :user

  #instance.mission 表示本隊的任務
  belongs_to :mission, counter_cache: true

  has_many :invitations
  has_many :invitees, through: :invitations

  has_many :instance_msgs

  has_many :reviews

  belongs_to :modifier, class_name: "User", optional: true

  scope :find_complete ,-> {
    where(state: 'complete')
  }

  def update_answer!(ans_params,user)
    self.update!(answer: ans_params[:answer], modifier: user)
  end


  # ::instance method:: 任務副本instance完成
  def complete!(user)
    return false if self.state != 'in_progress'
    # 用這種守衛提前返回的技巧，可以避免整個方法包在一個 if 裡面

    # 使用transaction打包交易，以免其中一項失敗，db可以rollback
    ActiveRecord::Base.transaction do
      self.state = 'complete'
      self.modifier = user
      self.save!

      #產生所有的review
      self.members.each do |reviewee|
        self.members.each do |reviewer|
          if reviewee != reviewer
            new_review = reviewee.reviews.build(instance_id: self.id)
            new_review.reviewer = reviewer
            new_review.save!
          end
        end
      end

      #更新xp及complete count
      self.members.each do |member|
        member.add_xp(self.xp)
        member.save!
        member.update_instances_completed_count!
      end
    end
  end

  def cancel!
    return false if self.state != 'teaming'

    ActiveRecord::Base.transaction do
      self.state = 'cancel'
      self.save!

      #取消緊急招募 - 未完成

      #取消所有人的邀請函
      self.invitations.find_inviting.each do |invitation|
        invitation.cancel!
        invitation.send_cancel_msg
      end
    end

  end


  # ::instance method::  任務副本instance終止
  def abort!(user)
    return false if self.state != 'in_progress'

    ActiveRecord::Base.transaction do
      self.state = 'abort'
      self.modifier = user  #觸發的使用者
      self.save!

      # 產生所有隊員的reivew
      self.members.each do |reviewee|
        self.members.each do |reviewer|
          if reviewee != reviewer
            new_review = reviewee.reviews.build(instance_id: self.id)
            new_review.reviewer = reviewer
            new_review.save!
          end
        end
      end
    end

  end


  # ::instance method:: 確認user為instance的成員
  def is_member?(user)
    members.include?(user)
  end

  # ::instance method:: 確認user可被邀請？
  def can_invite?(user)
    # ----說明----
    # 確認是否還有足夠的邀請函可以發送
    # 確認user為可接受邀本任務
    # 確認user不是 邀請中的使用者
    # 確認user不是member
    # ------------
    # 如果user可以接受任務
    # binding.pry
    if self.remaining_invitations_count <= 0
      #如果沒有邀請函可以發送，則不能邀請該user
      return false
    elsif user.take_mission?(self.mission)
      # user不在 邀請函是inviting 的集合中 且不是member, 就是可發送邀請
      return ( !self.invitees.where('invitations.state = ?','inviting').include?(user) ) &&  ( !self.members.include?(user) )
    else
      return false
    end
  end

  # ::instance method:: 列出所有可被邀請的使用者
  def invitable_users
    # ----說明----
    # 可邀請的user = 所有可執行user- 被邀請中的user - members
    # ------------
    users = User.where('available = ? AND level >= ?',true,self.mission.level )
    users = users - self.invitees.where('invitations.state = ?','inviting') - self.members
  end

  # ::instance method:: 列出所有發送邀請中的使用者
  def inviting_users
    self.invitees.where('invitations.state = ?','inviting')
  end

  # ::instance method:: 列出所有發送邀請中的邀請函
  def inviting_invitations
    self.invitations.where('state = ?', 'inviting')
  end
  # ::instance method:: 是否還有邀請函可以發送
  def remaining_invitations_count
    self.mission.invitation_number - self.inviting_invitations.count
  end

  def recipients
    # in_progress 有 save和沒save的狀況：
    #   save:除了自己的所有人
    # abort
    #   除了自己的所有人
    # complete
    #   所有人
    return_recipients = []
    return_recipients += self.members
    case self.state
    when 'in_progress'
      if self.modifier
        return_recipients.delete(self.modifier)
      end
    when 'abort'
      return_recipients.delete(self.modifier)
    end

    return_recipients
  end

  def actor
    # in_progress 有 save和沒save的狀況
    #  save: modifier
    # abort: modifier
    # complete: modifier
    if(self.modifier)
      return_actor = modifier
    else
      return_actor = User.find_by(email: 'admin@admin.com')
    end
    return_actor
  end

  def create_notifications
    # 通知
    # in_progress 有 save和沒save的狀況
    # abort
    # complete
    action = self.state
    if action == 'in_progress' ||action == 'abort' || action == 'complete'
      if self.modifier && action == 'in_progress' # save的狀況
        action = 'update_answer'
      end
      if self.members.count >1
        recipients.each do |recipient|
          Notification.create(recipient: recipient, actor: actor,
            action: action, notifiable: self)
        end
      end
    end
  end
  private
  # ::instance method:: 自動設定任務副本instance狀態
  def setup_state!
    #如果人數滿，組隊中會變成進行中

    #如果設定在after_commit 會造成查詢次數過多
    #這裡要想一下怎麼改會比較好
    # binding.pry
    if self.state == 'teaming'
    # 如果是人數已經滿了，則副本開始
      if self.members.length == self.mission.participant_number
        self.state = 'in_progress'
        self.save
        # 副本開始，其他邀請函取消
        # invitation.cancel inviting
        self.invitations.find_inviting.each do |invitation|
          invitation.cancel!
          invitation.send_cancel_msg
        end
      end
    end
  end


end

app/controllers/admin/instances_controller.rb
class Admin::InstancesController < Admin::BaseController
  def index
    @instances = Instance.all
  end
end

app/controllers/instances_controller.rb
class InstancesController < ApplicationController
  before_action :set_instance, except: [:history]
  before_action :authenticate_instance_member, except: [:history]

  def history
    @instances_history = current_user.instances.where(state: ['complete', 'abort'])
  end

  def show
    @mission = @instance.mission
    @members = @instance.members
    # if current_user.github_username
    #   @repos = current_user.github_repos
    # end
    # binding.pry
    if @instance.state == "teaming"
      # 篩選使用者 & 列出所有可被邀請的使用者
      @filterrific = filterrific_user or return
      @candidates = @filterrific.find.can_be_invited(@instance).page(params[:page]).per(20)
      # binding.pry
      # @instance.inviting_users 是正在邀請的使用者
      #所有邀情函
      @invitations = @instance.inviting_invitations.includes(:user)
      #剩下可發送的邀請函數量
      @remaining_invitations_count = @instance.remaining_invitations_count

      respond_to do |format|
        format.html
        format.js
      end

    end

    if @instance.state == 'in_progress'
      #只有任務進行中可以留言
      @instance_msg = InstanceMsg.new

      #答案
      @answer = @instance.answer
    end

    if @instance.state == 'in_progress' || @instance.state == 'abort' || @instance.state == 'complete'
      # 組隊完成後，才可以瀏覽留言
      @instance_msgs = @instance.instance_msgs
    end

    if @instance.state == 'abort' || @instance.state == 'complete'
      # 完成後才可到評論頁面
      # 其他人對current_user的review
      @reviews = current_user.reviews.find_by_instance(@instance)
      #current_user對其他人的review
      @reviews_to_other = current_user.review_to_members.find_by_instance(@instance)
    end

  end


  def save
    if @instance.state == "in_progress"
      @instance.update_answer!(submit_params,current_user)
    else
      flash[:alert] = "存取禁止"
      redirect_back(fallback_location: root_path)
    end

  end

  def edit
    render :edit
  end

  def submit
    # 需要為成員而且副本狀態是進行中才能夠提交副本
    # binding.pry
    if @instance.state == "in_progress"
      if !@instance.answer.strip.empty?
        flash[:notice] = "任務完成！"
        # 更改instance狀態

        @instance.complete!(current_user)
        redirect_to instance_path(@instance)
      else
        flash[:alert] = "提交失敗！"
        redirect_to instance_path(@instance)
      end
    else
      flash[:alert] = "存取禁止"
      redirect_back(fallback_location: root_path)
    end
  end

  def cancel
    #取消組隊
    #取消後，其他邀請函會自動取消
    if @instance.state == 'teaming'
      flash[:notice] = '放棄組隊！'
      @instance.cancel!
      # binding.pry
      recruit_board = RecruitBoard.find_by(user_id: current_user.id, instance_id: @instance.id)
      # 如果這個任務有對應到招募的話便把招募刪除
      recruit_board.delete if recruit_board
      redirect_to instance_path(@instance)
    else
      flash[:alert] = "存取禁止"
      redirect_back(fallback_location: root_path)
    end

  end

  def abort
  # 放棄任務
    #使用者可以直接中止任務
    if @instance.state == 'in_progress'
      #確認副本是in_progress
      @instance.abort!(current_user)
      flash[:notice] = "任務中止"
      # 回到instance#show
      redirect_to instance_path(@instance)
    #不是成員
    else
      flash[:alert] = "存取禁止"
      redirect_back(fallback_location: root_path)
    end
  end



  private
  def submit_params
    params.require(:instance).permit(:answer)
  end

  def set_instance
    @instance = Instance.find(params[:id])
  end

  def authenticate_instance_member
    #驗證是不是副本成員
    if !@instance.is_member?(current_user)
      flash[:alert] = '::instance:: 存取禁止！'
      redirect_back(fallback_location: root_path)
    end
  end

end

app/helpers/admin/instances_helper.rb
module Admin::InstancesHelper
end

app/helpers/instances_helper.rb
module InstancesHelper
  def abort_button(instance)
    if instance.present?
      if instance.state == 'in_progress'
        link_to('放棄任務', abort_instance_path, method: :post, class: "btn bg-danger-dark btn-oval", data: { confirm: "跟組員溝通過了嗎，確定要放棄任務？" })
      end
    end
  end

  def cancel_button(instance)
    if instance.present?
      if instance.state == 'teaming'
        link_to('放棄組隊', cancel_instance_path, method: :post, class: "btn bg-danger-dark btn-oval", data: { confirm: "放棄組隊後，所有邀請函皆會失效。\n\n確定要放棄組隊？" })
      end
    end
  end

  def instance_title(instance)
    case instance.state
    when 'teaming' then '組員招募中'
    when 'in_progress' then '任務進行中'
    when 'complete' then '任務已完成'
    when 'cancel' then '取消組隊'
    when 'abort' then '任務已放棄'
    end
  end

  def transcript_instance_state(instance)
    case instance.state
    when 'teaming' then '組隊中'
    when 'in_progress' then '進行中'
    when 'complete' then '已完成'
    when 'abort' then '已放棄'
    end
  end

  def enter_instance(instance)
    case instance.state
      when 'teaming'
        link_to "招募探員", instance_path(instance), class: "btn btn-primary"
      when 'in_progress'
        link_to "進行任務", instance_path(instance), class: "btn btn-primary"
      else
        link_to "任務詳情", instance_path(instance), class: "btn btn-primary"
      end
  end

  def user_already_done(instance, user)
    if user.missions_compeleted.include?(instance.mission)
      content_tag(:span, '已完成過' , class: "badge badge-success mb-2")
    end
  end

  def user_in_progress(instance, user)
    if user.missions_in_progress.include?(instance.mission)
      content_tag(:span, '正執行中' , class: "badge badge-success mb-2")
    end
  end

  def user_already_decline(instance, user)
    if user.was_declined?(instance)
      content_tag(:span, '已拒絕' , class: "badge badge-danger mb-2")
    end
  end

  def instance_member_names(instance)
    instance.members.map {|member| member.name }.join(", ")
  end

  def progress_num(instance)
    if instance.state == 'teaming'
      '25'
    elsif instance.state == 'in_progress' && instance.answer == ''
      '50'
    elsif instance.state == 'in_progress' && instance.answer != ''
      '75'
    elsif instance.state == 'complete' && instance.reviews.where(submit: false).present?
      '90'
    elsif instance.state == 'complete'
      '100'
    else
      '0'
    end
  end

  def review_submited?(instance,user)
    reviews = instance.reviews.find_by(reviewer_id: user)
    if reviews.present? && !reviews.submit?
      true
    else
      false
    end
  end



end

app/views/instances/_ans_form.html.erb
<%=simple_form_for instance, remote: true, url: save_instance_path(instance),method: :post do |f| %>
  <%= f.input :answer, required: true %>
  <div class="mt-4">
  <%= f.button :submit, '儲存', class: "btn btn-primary" %>
  <%if current_user.have_github_username? %>
    <div id="get_repos" class='btn btn-inverse' ><a href="#github_form_window"><span class='fa fa-github fa-lg'></span></a></div>

  <%end%>
  </div>
<%end%>



<%if current_user.have_github_username? %>
<div id="github_form_window" class="github-overlay ">
  <div class="github-popup ">
    <h3>從你的github選答案</h3>
    <span class="close" href="#">&times;</span>
    <div class="content">
      <form class="form-inline" id="repos_select_show">
        <div class="sk-circle">
          <div class="sk-circle1 sk-child"></div>
          <div class="sk-circle2 sk-child"></div>
          <div class="sk-circle3 sk-child"></div>
          <div class="sk-circle4 sk-child"></div>
          <div class="sk-circle5 sk-child"></div>
          <div class="sk-circle6 sk-child"></div>
          <div class="sk-circle7 sk-child"></div>
          <div class="sk-circle8 sk-child"></div>
          <div class="sk-circle9 sk-child"></div>
          <div class="sk-circle10 sk-child"></div>
          <div class="sk-circle11 sk-child"></div>
          <div class="sk-circle12 sk-child"></div>
        </div>
      </form>
    </div>
  </div>
</div>




<script>
$(document).ready(function(){

  var input = document.getElementById("instance_answer");
  var select_show = document.getElementById("repos_select_show");
  var getReposBtn =document.getElementById("get_repos");
  var loading_template = document.getElementById("loading_template");
  var popupWindow = document.getElementById("github_form_window");
  var closepopup = document.querySelector(".github-popup span.close");
  closepopup.addEventListener('click',(e)=>{popupWindow.classList.remove('show')});
  var formTemplate = document.getElementById("github_select_template");
  getReposBtn.addEventListener('click', getGithubRepo);
  function getGithubRepo(e){
    // console.log("click getGithubRepo");
    popupWindow.classList.toggle('show');

    $.ajax({
      url: "/users/<%=current_user.id%>/repos.json",
      dataType: "JSON",
      method: "GET",
      success: (data)=>{
        let new_select = document.createElement("select");
        new_select.id = 'repos_input';
        data.forEach((repo_data)=>{
          let new_option = document.createElement('option');
          new_option.value = repo_data.repo_url;
          new_option.textContent = repo_data.repo_name;
          // console.log(new_option);
          new_select.appendChild(new_option);
        });
        new_select.className="form-control";
        new_btn = document.createElement("button");
        new_btn.addEventListener('click',selectRepo);
        new_btn.className = 'btn btn-primary m-2';
        new_btn.innerHTML = '確定';
        select_show.innerHTML=new_select.outerHTML;
        select_show.appendChild(new_btn);

      }
    });
  }

  function selectRepo(e){
    e.preventDefault();
    let repos_input = document.getElementById('repos_input');
    input.value = repos_input.value;
    popupWindow.classList.toggle('show');
  }
})
  
</script>
<%end%>

app/views/instances/_ans_panel.html.erb
<form>
  <fieldset disabled>
    <div class="form-group">
      <label for="disabledTextInput">Answer</label>
        <% if instance.modifier %>
          <div class="info d-inline float-right"><small><em><%=instance.modifier.name%> 於 <%= instance.updated_at%> 更新了答案</em></small></div>
        <%end%>
      <input type="text" id="disabledTextInput" class="form-control" placeholder="<%=instance.answer%>">
    </div>
  </fieldset>
</form>
<%= link_to '再次編輯', edit_instance_path(instance),remote: true, class: "btn btn-outline-primary " %>
<%= link_to "提交任務成果", submit_instance_path(@instance),method: :post, class: "btn btn-primary ml-2" ,data: {confirm: '提交任務後就不能修改，你有跟組員充分溝通嗎？'}%>

app/views/instances/_candidates_list.html.erb
<div id="filterrific_results" >
  <div class="col card bg-inverse-light">
    <div class="card-body d-flex justify-content-between p-3">
      <p><%= page_entries_info candidates  %></p>
      <%= link_to 'Reset filters', reset_filterrific_url, class: "btn btn-outline-light" %>
    </div>
  </div>

  <div class="row mb-4">
    <% candidates.each do |user| %>
      <div class="col-xs-12 col-sm-6 col-lg-4  my-3" id="filterrific_results">
        <%= render partial:"shared/user_card" , locals: {user: user } %>
      </div>
    <% end %>
  </div>
  <%= paginate candidates %>
</div>

app/views/instances/_instance_msg_board.html.erb
<div class="row mb-4">
  <div class="col-12 my-3">
    <div class="d-flex justify-content-between">
      <div class=""><h4>任務筆記與留言</h4></div>
      <div class=""><span class="ml-2 fa fa-question-circle  " title="" data-container="body" data-trigger='hover' data-toggle="popover" data-placement="top" data-content="可以留下自己的筆記（本欄支援markdown語法），或者與您的夥伴交換任務資訊。"> </span></div>
    </div>
  </div>
  <div class="col-12">
    <% @instance_msgs.each do |msg| %>
      <div class="col-12 m-0">
        <div class="table-responsive">
          <table class="table m-0">
            <tbody>
              <tr>
                <td class="b0 wd-xs d-md-table-cell text-center">
                  <%= gravatar_for(msg.user, "img-fluid rounded-circle img-thumbnail thumb48") %><br>
                  <span><%= msg.user.name %></span>
                </td>
                <td class="b0">
                  <div class="bg-gray-darker px-3 py-2 rounded ">
                    <span ><%= to_markdown(msg.content) %></span>
                  </div>
                  <span class="text-muted mt-1"><%= time_ago_in_words(msg.updated_at) + '前' %></span>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    <% end %>
  </div>
</div>

<% if @instance.state == 'in_progress' %>
  <%= simple_form_for @instance_msg ,url: instance_instance_msgs_path(@instance) do |f| %>
    <%= f.input :content, label: false, placeholder:'留下筆記留言...'%>
    <%= f.button :submit, '送出', class:"btn btn-primary" %>
  <%end%>
<% end %>

<!-- <script>
  // 按enter可以直接送出
  $('#new_instance_msg').keypress(function (e) {
        if(e.which == 13 && !e.shiftKey) {
            // e.form.submit();
            console.log(e);
            e.preventDefault()
            $('#new_instance_msg').submit();
        }
    });
</script> -->

app/views/instances/_leave_review.html.erb
<div class="card card-default" id="<%= 'card-anim-bounce' if review_submited?(@instance,current_user) %>" >
  <div class="card-body bb pb-0">
    <div class="clearfix">
      <div class="float-left">
        <h4>任務評價</h4>
      </div>
    </div>
  </div>

  <div class="card-body bb">
    <% @reviews_to_other.each do |review| %>
      <% if review.submit? %>
        <h4>你對 <%=review.reviewee.name%> 的評價：</h4>
        <p><%= print_rating_stars review.rating%></p>
        <p><%= review.comment %></p>
      <% else %>
        <p>這次的任務，你覺得 <%= review.reviewee.name %> 的表現如何?</p>


        <%= simple_form_for review, url: submit_review_path(review) do |f| %>
          <div class="review_rating from-group">
            <label for="star5" title="Excellent!">
            <%=f.radio_button :rating, 5, :id => "star5" %>5 Stars</label>
            <label for="star4" title="Good!">
            <%=f.radio_button :rating, 4, :id => "star4" %> 4 Stars</label>
            <label for="star3" title="Average!">
            <%=f.radio_button :rating, 3, :id => "star3" %> 5 Stars</label>
             <label for="star2" title="Poor!">
            <%=f.radio_button :rating, 2, :id => "star2" %>2 Stars</label>
            <label for="star1" title="Very Poor!">
            <%=f.radio_button :rating, 1, :id => "star1" %> 1 Stars</label>
          </div>
          <%= f.input :comment, label: false, placeholder:'給個評語吧...'%>
          <%= f.button :submit, '送出', class:"btn btn-primary" %>
        <% end %>
      <% end %>
    <% end %>
  </div>

  <div class="card-body bb">
    <h4>組員對你的評價：</h4>
    <% if @reviews_to_other.first.submit? %>
      <% @reviews.each do |review| %>
        <% if review.submit? %>
          <%= render partial: 'shared/review_card', locals:{review: review} %>
        <% else %>
          <p><%= review.reviewer.name %> 尚未提供評價</p>
        <% end %>
      <%end%>
    <% else %>
      <p>雙方皆提供評價後，才會顯示組員給你的評語喔！</p>
    <% end %>
  </div>
</div>
<script>
  $('.review_rating input').change(function () {
    var $radio = $(this);
    //console.log($radio.closest('label'));
    $('.review_rating .selected').removeClass('selected');
    $radio.closest('label').addClass('selected');
  });
  $('#card-anim-bounce').animo({ animation: "bounce", delay: 0.5 });
</script>

app/views/instances/_list.html.erb
<div id="filterrific_results" >
  <div class="rowmb-4">
    <div class="col card bg-light ">
      <div class="card-body d-flex justify-content-between p-3">
        <p><%= page_entries_info candidates  %></p>
        <%= link_to 'Reset filters', reset_filterrific_url, class: "btn btn-outline-secondary" %>
      </div>
    </div>
  </div>

  <div class="row mb-4">
    <% candidates.each do |user| %>
      <div class="col-xs-12 col-sm-6 col-lg-4 col-xl-3 my-3" id="filterrific_results">
        <%= render partial:"shared/user_card" , locals: {user: user} %>
        <%= button_to "邀請" , invite_user_path(user), params: {instance_id: @instance.id}, class: "btn btn-primary" if @remaining_invitations_count > 0 %>
      </div>
    <% end %>
  </div>
</div>

app/views/instances/_member_info.html.erb
<div class="row mb-4">
  <div class="col-12">
    <h3>副本成員</h3>
  </div>
  <% members.each do |member| %>
    <div class="col-xs-12 col-sm-6 col-lg-4 col-xl-3 my-3">
      <%= render partial:"shared/user_card" , locals: {user: member} %>
    </div>
  <% end %>
</div>

app/views/instances/_member_list.html.erb
<h4>任務成員</h4>
<div class="row mt-3">
  <% members.each do |member| %>
    <div class="col-4 col-md-3 col-lg-2 text-center mb-3">
      <%= render partial:"shared/user_head" , locals: {user: member} %>
    </div>
  <% end %>
</div>

app/views/instances/_mission_info.html.erb
<div class="card card-default">
  <div class="card-body bb">
    <div class="clearfix">
      <div class="float-left">
        <h4><%= @mission.name %></h4>
        <%= render partial: 'shared/mission_tags', locals: {mission: @mission} %>
      </div>
      <div class="float-right">
        <%= abort_button(@instance) %><%= cancel_button(@instance) %>
      </div>
    </div>
  </div>
  <div class="card-body bb">
    <%= image_tag @mission.image_url, class: "rounded img-fluid my-3" %>
    <p><%= truncate @mission.description, length: 300 %> <%= link_to "任務詳情", mission_path(@mission), remote: true %></p>
  </div>
  <div class="card-body">
    <p ><strong>任務進度<strong></p>
    <div class="d-flex align-items-center">
      <div class="w-100">
        <div class="progress progress-xs m-0">
          <div class="progress-bar bg-warning-dark" style="width:<%= progress_num(@instance) %>%;"></div>
        </div>
      </div>
      <div class="wd-xxs text-right">
        <div class="text-bold text-muted"><%= progress_num(@instance) %>%</div>
      </div>
    </div>
  </div>
  <table class="table">
    <tbody>
      <tr>
        <td>
          <strong>Level</strong>
        </td>
        <td><%= @mission.level %></td>
      </tr>
      <tr>
        <td>
          <strong>任務人數</strong>
        </td>
        <td><%= @mission.participant_number %></td>
      </tr>
      <tr>
        <td>
          <strong>XP</strong><span class="float-right fa fa-question-circle  " title="" data-container="body" data-trigger='hover' data-toggle="popover" data-placement="top" data-content="完成本次任務後你即可獲得的經驗值。"> </span>
        </td>
        <td><%= @mission.xp %></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/instances/_teaming.html.erb
<%= render partial: "member_info", locals:{members: @members} %>

<div class="row mb-4">
  <div class="col-12">
    <h3>已經送出邀請</h3>
  </div>
  <% @invitations.each do |invitation| %>
    <div class="col-xs-12 col-sm-6 col-lg-4 col-xl-3 my-3">
      <%= render partial:"shared/user_card" , locals: {user: invitation.invitee} %>
      <%= link_to '聊聊', invitation_path(invitation), remote: true, class: 'btn btn-primary' %>
      <%= link_to '取消邀請', cancel_invitation_path(invitation), method: :post, class: 'btn btn-danger' %>
    </div>
  <% end %>
</div>

<div class="row mb-4">
  <div class="col-12">
    <h3>可選隊員 </h3>
    <h5><span class="badge badge-info">你還可發送 <%=@remaining_invitations_count%> 張邀請</span></h5>
  </div>
</div>

<div class="row mb-4 ">
  <div class="col bg-light card mx-3">
    <%= form_for_filterrific @filterrific do |f| %>
    <div class="form-row card-body">
        <div class="col-md-3 form-group" data-intro="Search by name or email." data-position="top">
          <label>Search</label>
          <%= f.text_field :search_query, class: "form-control" %>
        </div>

        <div class="form-group col-md-3" >
          <label>Gender</label>
          <%= f.select(:with_gender, @filterrific.select_options[:with_gender],
            { include_blank: '- 不限 -' }, {class: "form-control"}
          ) %>
        </div>

        <div class="form-group col-md-3" >
          <label>Level</label>
          <%= f.select(:range_level, @filterrific.select_options[:range_level],
            { include_blank: '- 不限 -' }, {class: "form-control"}
          ) %>
        </div>

        <div class="form-group col-md-3" >
          <label>Sorted by</label>
          <%= f.select(:sorted_by, @filterrific.select_options[:sorted_by],{}, {class: "form-control"} ) %>
        </div>
      </div>
      <%= render_filterrific_spinner %>
    <% end %>
  </div>
</div>

<%= render( partial: 'list', locals: { candidates: @candidates } ) %>

<div class="modal fade" id="invitation_model" tabindex="-1" role="dialog" aria-labelledby="ShowMissionModal" aria-hidden="true"></div>

app/views/instances/edit.js.erb
<% html = j( render :partial => "ans_form", :locals => { instance: @instance } ) %>
$(".instance_ans").html("<%= html %>")