config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'instances/index'
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks", confirmations: "confirmations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  authenticated :user do
    root "missions#dashboard"
  end

  root 'public#landing'
  get 'story', :to => 'public#story'
  resources :announcements, only: [:show]
  resources :notifications do
    collection do
      post :mark_as_checked_all
      post :mark_as_read_all
    end
    member do
      post :mark_as_read
    end
  end
  resources :invitations, only: [:index, :show] do
    member do
      post :accept
      post :decline
      post :cancel
      post :read_all_msg
    end
    collection do
      get :sent_index
    end
    resources :invite_msgs, only: [:create]
  end
  resources :invite_msgs, only: [:show]
  resources :instances, only: [:show, :edit] do
    member do
      post :submit
      patch :submit  #任務完成，提交答案
      post :save
      post :cancel   #取消組隊
      post :abort    #放棄任務
    end

    collection do
      get :history
    end
    resources :instance_msgs, only: [:create]
  end

  resources :followships, only: [:create, :destroy]

  resources :missions, only: [:index, :show] do
    member do
      get :dashboard
      post :challenge
      get :select_user
      # POST challenge_mission_path 挑戰本任務
    end

    collection do
      get :teaming
    end
  end

  resources :reviews, only: [:index, :show] do
    member do
      patch :submit
    end
  end

  resources :users do
    member do
      post :invite
      get :repos
    end
  end

  namespace :admin do
    root "missions#index"
    resources :missions
    resources :instances, only: [:index]
    resources :announcements
  end

  resources :recruit_boards, only: [:index, :create, :destroy] do
    member do
      post :accept
    end
  end

  mount ActionCable.server => '/cable'

end

app/views/shared/_filterrific_user_form.html.erb
<div class="row mb-0">
  <div class="col bg-inverse-light card mx-3">
    <%= form_for_filterrific @filterrific, remote: true do |f| %>
      <div class="form-row card-body">
        <div class="form-group col-md-4" data-intro="Search by name or email." data-position="top">
          <h5>搜尋 姓名 或 Email</h5>
          <%= f.text_field :search_query, class: "form-control" %>
        </div>
        <div class="form-group col-md-4" >
          <h5>探員位置</h5>
          <%= f.select(:with_location, @filterrific.select_options[:with_location],{}, {class: "form-control"} ) %>
        </div>
        <div class="form-group col-md-4" >
          <h5>排序</h5>
          <%= f.select(:sorted_by, @filterrific.select_options[:sorted_by],{}, {class: "form-control"} ) %>
        </div>
        <div class="form-group col-lg-6" >
          <h5>探員類型</h5>
          <div class="btn-group btn-group-toggle" data-toggle="buttons">
            <label class="btn btn-dark <%= 'active' if @filterrific.with_friendtype.blank? %> ">
              <%= f.radio_button :with_friendtype, '' %> 不限
            </label>
            <label class="btn btn-dark <%= 'active' if @filterrific.with_friendtype == "#{current_user.id}_oldteam" %> ">
              <%= f.radio_button :with_friendtype, "#{current_user.id}_oldteam" %> 老隊友
            </label>
            <label class="btn btn-dark <%= 'active' if @filterrific.with_friendtype == "#{current_user.id}_following" %> ">
              <%= f.radio_button :with_friendtype, "#{current_user.id}_following" %> 我在追蹤
            </label>
            <label class="btn btn-dark <%= 'active' if @filterrific.with_friendtype == "#{current_user.id}_follower" %> ">
              <%= f.radio_button :with_friendtype, "#{current_user.id}_follower" %> 追蹤我
            </label>
          </div>
        </div>
        <div class="form-group col-lg-6" >
          <h5>等級</h5>
          <div class="btn-group btn-group-toggle" data-toggle="buttons">
            <label class="btn btn-dark <%= 'active' if @filterrific.with_level.blank? %> ">
              <%= f.radio_button :with_level, '' %> 不限
            </label>
            <% @filterrific.select_options[:with_level].each do |level| %>
                <%= f.label level[0] ,class: "btn btn-dark #{'active' if @filterrific.with_level.to_s == level[1]}" do %>
                  <%= f.radio_button :with_level, level[1] %> <%= level[0] %>
                <% end %>
            <% end %>
          </div>
        </div>


      </div>
      <%= render_filterrific_spinner %>
    <% end %>
  </div>
</div>

app/views/shared/_follow.html.erb
<% if user != current_user%>
  <% if current_user.following?(user) %>
    <%= link_to '停止追蹤', followship_path(user), method: :delete, class: "btn btn-outline-danger" %>
  <% else %>
    <%= link_to '開始追蹤', followships_path(following_id: user), method: :post, class: "btn btn-outline-primary" %>
  <% end %>
<% end %>

app/views/shared/_instance_card.html.erb
<% if instances.present? %>
  <% instances.each do |instance| %>
    <div class="col-12 my-2">
      <div class="card" >
        <div class="row">
          <div class="col-4 pr-0">
            <div class="card-body h-100 card-img-left" style="background-image: url(<%= instance.mission.image_url %>);" ></div>
          </div>
          <div class="col-8 pl-0">
            <div class="card-body">
              <h5 class="card-title"><%= link_to instance.mission.name, instance_path(instance) %></h5>
              <p class="card-text"><span class="badge badge-success">Level <%= instance.mission.level %></span> <span class="badge badge-success">Team# <%= instance.mission.participant_number %></span></p>
              <p class="card-text"><%= truncate instance.mission.description, length: 60 %></p>
              <%= enter_instance(instance) %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <%end%>
<% else %>
  <div class="col-12">
    <p>無</p>
  </div>
<% end %>

app/views/shared/_instance_list.html.erb
<% if instances.present? %>
  <div class="col-12 my-3">
    <table class="table table-hover" id="instance_list">
      <thead class="thead-dark">
        <tr>
          <th scope="col">任務名稱</th>
          <th scope="col">任務等級</th>
          <th scope="col">任務人數</th>
          <th scope="col">描述</th>
          <th scope="col">執行成果</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <% instances.each do |instance| %>
          <tr>
            <td><%= link_to instance.mission.name, instance_path(instance) %></th>
            <td><%= instance.mission.level %></td>
            <td><%= instance.mission.participant_number %></td>
            <td><%= truncate instance.mission.description, length: 40 %></td>
            <td><%= instance.state %></td>
            <td><%= enter_instance(instance) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <div class="col-12 my-3">
    <p>無</p>
  </div>
<% end %>

app/views/shared/_mission_card.html.erb
<div class="card">
  <div class="card-body text-center bg-center" style="background-image: url(<%= mission.image_url %>);">
    <div class="row">
      <div class="col-12 text-white" style="height: 100px;">

      </div>
    </div>
  </div>
  <div class="card-body bg-gray-dark">
  <h4 class="m-0"><%= mission.name %></h4>
  </div>
  <div class="row text-center p-2">
    <div class="col-4">
      <p class="m-0 text-muted">Level</p>
      <p class="m-0 h3"><%= mission.level %></p>
    </div>
    <div class="col-4">
      <p class="m-0 text-muted">Team #</p>
      <p class="m-0 h3"><%= mission.participant_number %></p>
    </div>
    <div class="col-4">
      <p class="m-0 text-muted">XP</p>
      <p class="m-0 h3"><%= mission.xp %></p>
    </div>
  </div>
  <div class="row px-3 py-1">
    <div class="col-12 mb-2">
      <%= render partial: 'shared/mission_tags', locals: {mission: mission} %>
    </div>
    <div class="col-12">
      <p><%= truncate mission.description, length: 80 %></p>
    </div>
  </div>
  <div class="row p-2 text-center">
    <div class="col-12">
      <p>
        <%= link_to "任務詳情", mission_path(mission), remote: true, class: "btn bg-gray-darker mr-2" %>
        <%= challenge_button(mission,@user) %>
      </p>
    </div>
  </div>
</div>

app/views/shared/_mission_tags.html.erb
<% mission.tag_list.each do |tag| %>
    <span class="badge px-2 bg-gray-darker"><%= tag %></span>
<% end %>

app/views/shared/_notify_for_ajax.html.erb
<% if @notice_msg %>
$.notify({
  message : '<%= @notice_msg %>',
  status  : 'success',
  timeout : 3000,
  pos     : 'top-center'
});
<% end %>
<% if @alert_msg %>
$.notify({
  message : '<%= @alert_msg %>',
  status  : 'danger',
  timeout : 3000,
  pos     : 'top-center'
});
// pos: 'top-center', 'top-left', 'top-right', 'bottom-center', 'bottom-left', 'bottom-right'
<% end %>

app/views/shared/_recruit_board_card.html.erb
<div class="card b text-center mb-2">
  <div class="card-body">
    <%= gravatar_for(recruit_board.user, "rounded-circle thumb64 mb-2") %>
    <p class="h4 text-bold">發起人：<%= link_to recruit_board.user.name, user_path(recruit_board.user), remote: true %></p>
  </div>
  <div class="card-body bt">
    <div class="row">
      <div class="col-4 br">

        <strong class="text-success">
        <%= link_to '任務詳情', recruit_board.instance.mission, remote: true  %>
        </strong><br>

      </div>
      <div class="col-4 br">
        <% if recruit_board.user == current_user %>
          <%= link_to '取消本次徵召', recruit_board_path(recruit_board), method: :delete, class: 'btn btn-danger' %>
        <% else %>
          <%= link_to '接受徵召', accept_recruit_board_path(recruit_board), method: :post, class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_review_card.html.erb
<div class="card col-12 ">
  <div class="table-responsive">
    <table class="table">
      <tbody>
        <tr>
          <td class="b0 wd-xs d-none d-md-table-cell text-center">
            <%= link_to user_path(review.reviewer), remote: true do %>
              <%= gravatar_for(review.reviewer, "img-fluid rounded-circle img-thumbnail") %>
              <span><%= review.reviewer.name %></span>
            <% end %>
          </td>
          <td class="b0">
            <% if controller?('users') && action?('show') %>
              <p class="h4 mt-0">
                <%= link_to review.instance.mission.name ,mission_path(review.instance.mission), remote: true %>
                <span class="rounded badge bg-gray-dark px-2 ml-2 text-sm d-none d-lg-inline text-muted">
                <span class="text-muted">Mission <%= review.instance.state %></span>
                </span>
              </p>
            <% end %>
            <div><%= print_rating_stars review.rating %></div>
            <div><%= review.comment %></div>
            <div class="text-muted mt-1"> - <%= time_ago_in_words(review.updated_at) + '前' %></div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/shared/_user_card.html.erb
<div class="card b text-center mb-2">
  <div class="card-body user-block">
    <div class="user-block-picture w-50">
      <%= link_to gravatar_for(user,"img-thumbnail rounded-circle thumb80 mb-2"), user_path(user), remote: true %>
      <div class='user-block-status'>
        <% if user.available %>
          <div class="circle bg-success circle-lg" data-toggle="tooltip" data-placement="right" title="狀態：接受任務邀請"></div>
        <% else %>
          <div class="circle bg-danger circle-lg" data-toggle="tooltip" data-placement="right" title="狀態：不接受邀請"></div>
        <% end %>
      </div>
    </div>
    <p class="h4 text-bold"><%= link_to user.name, user_path(user), remote: true %><%= content_tag(:span, 'Me' , class: "badge bg-gray-darker ml-2") if user == current_user%></p>
    <% if @instance.present? %>
      <p class="mb-0">
        <%= user_already_done(@instance, user) %>
        <%= user_in_progress(@instance, user) %>
        <%= user_already_decline(@instance, user) %>
      </p>
    <% end %>
  </div>
  <div class="card-body bt">
    <div class="row">
      <div class="col-4 br">
        <strong class="text-primary">Level</strong><br>
        <strong><%= user.level %></strong>
      </div>
      <div class="col-4 br">
        <strong class="text-success">XP</strong><br>
        <strong><%= user.xp %></strong>
      </div>
      <div class="col-4">
        <strong class="text-warning">評價</strong><br>
        <strong><%= user.average_rating_count %></strong>
      </div>
    </div>
  </div>
</div>
<div class='d-flex justify-content-center my-3'>
  <%= render partial: "shared/follow", locals: {user: user} %>
    <% if @instance.present? %>
    <%= button_to "邀請" , invite_user_path(user), params: {instance_id: @instance.id }, remote: true, data: { disable_with: '送出邀請...' }, class: "ml-2 btn btn-primary" if @remaining_invitations_count > 0 %>
  <% elsif @invitation.present? %>
    <!-- 不顯示任何項目 -->
  <% else %>
    <% if user != current_user%>
      <% if  user.available == true  %>
        <%= link_to "邀請組隊", teaming_missions_path(user_id: user.id), class: "btn btn-primary ml-2" %>
      <% else %>
        <button class="btn btn-dark ml-2 disabled" >探員忙碌中</button>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/shared/_user_head.html.erb
<div class="user-head mb-2" >
  <div class="row">
    <div class="col text-center">
      <%= link_to user_path(user), remote: true do%>
        <%= gravatar_for(user, "img-thumbnail rounded-circle thumb64")  %><br>
      <% end %>
      <span><%= link_to user.name, user_path(user), remote: true %></span>
    </div>
  </div>
</div>

app/views/shared/_user_rating.html.erb
<div class="col-12 col-sm-6 mb-3 mb-sm-0 rating">
  <span class="rating-num"><%=user.average_rating_count%></span>
  <div class="rating-stars">
    <%= print_rating_stars user.average_rating_count.round.to_i %>
  </div>
  <div class="rating-users">
    <i class="icon-user"></i> 共有<%=rating_count.sum%>則評價
  </div>
</div>
<div class="col-12 col-sm-6 histo">
  <div class="five histo-rate">
    <span class="histo-star">
      <i class="active icon-star"></i> 5</span>
    <span class="rating-bar-block">
      <span id="rating-bar-five" class="rating-bar">
        <span class="ml-2"><%=rating_count[4]%></span>&nbsp;
      </span>
    </span>
  </div>
  <div class="four histo-rate">
    <span class="histo-star">
      <i class="active icon-star"></i> 4 </span>
    <span class="rating-bar-block">
      <span id="rating-bar-four" class="rating-bar">
        <span class="ml-2"><%=rating_count[3]%></span>&nbsp;
      </span>
    </span>
  </div>
  <div class="three histo-rate">
    <span class="histo-star">
      <i class="active icon-star"></i> 3</span>
    <span class="rating-bar-block">
      <span id="rating-bar-three" class="rating-bar">
        <span class="ml-2"><%=rating_count[2]%></span>&nbsp;
      </span>
    </span>
  </div>
  <div class="two histo-rate">
    <span class="histo-star">
      <i class="active icon-star"></i> 2</span>
    <span class="rating-bar-block">
      <span id="rating-bar-two" class="rating-bar">
        <span class="ml-2"><%=rating_count[1]%></span>&nbsp;
      </span>
    </span>
  </div>
  <div class="one histo-rate">
    <span class="histo-star">
      <i class="active icon-star"></i> 1</span>
    <span class="rating-bar-block">
      <span id="rating-bar-one" class="rating-bar">
        <span class="ml-2"><%=rating_count[0]%></span>&nbsp;
      </span>
    </span>
  </div>
</div>

<script>
  $(document).ready(function() {
  $('.rating-bar span').hide();
  <% if rating_count.sum > 0 %>
    $('#rating-bar-five').animate({
       width: '<%= ((rating_count[4].to_f / rating_count.sum.to_f) * 100.0).round %>%'}, 1000);
    $('#rating-bar-four').animate({
       width: '<%= ((rating_count[3].to_f / rating_count.sum.to_f) * 100.0).round %>%'}, 1000);
    $('#rating-bar-three').animate({
       width: '<%= ((rating_count[2].to_f / rating_count.sum.to_f) * 100.0).round %>%'}, 1000);
    $('#rating-bar-two').animate({
       width: '<%= ((rating_count[1].to_f / rating_count.sum.to_f) * 100.0).round %>%'}, 1000);
    $('#rating-bar-one').animate({
       width: '<%= ((rating_count[0].to_f / rating_count.sum.to_f) * 100.0).round %>%'}, 1000);
  <%end%>
  
  setTimeout(function() {
    $('.rating-bar span').fadeIn('slow');
  }, 1000);

});
</script>