config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'instances/index'
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks", confirmations: "confirmations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  authenticated :user do
    root "missions#dashboard"
  end

  root 'public#landing'
  get 'story', :to => 'public#story'
  resources :announcements, only: [:show]
  resources :notifications do
    collection do
      post :mark_as_checked_all
      post :mark_as_read_all
    end
    member do
      post :mark_as_read
    end
  end
  resources :invitations, only: [:index, :show] do
    member do
      post :accept
      post :decline
      post :cancel
      post :read_all_msg
    end
    collection do
      get :sent_index
    end
    resources :invite_msgs, only: [:create]
  end
  resources :invite_msgs, only: [:show]
  resources :instances, only: [:show, :edit] do
    member do
      post :submit
      patch :submit  #任務完成，提交答案
      post :save
      post :cancel   #取消組隊
      post :abort    #放棄任務
    end

    collection do
      get :history
    end
    resources :instance_msgs, only: [:create]
  end

  resources :followships, only: [:create, :destroy]

  resources :missions, only: [:index, :show] do
    member do
      get :dashboard
      post :challenge
      get :select_user
      # POST challenge_mission_path 挑戰本任務
    end

    collection do
      get :teaming
    end
  end

  resources :reviews, only: [:index, :show] do
    member do
      patch :submit
    end
  end

  resources :users do
    member do
      post :invite
      get :repos
    end
  end

  namespace :admin do
    root "missions#index"
    resources :missions
    resources :instances, only: [:index]
    resources :announcements
  end

  resources :recruit_boards, only: [:index, :create, :destroy] do
    member do
      post :accept
    end
  end

  mount ActionCable.server => '/cable'

end

app/models/invitation.rb
class Invitation < ApplicationRecord
  after_commit :setup_state!
  #after_commit {binding.pry}
  after_commit :create_notifications
  belongs_to :user
  belongs_to :instance
  belongs_to :invitee, class_name: "User"
  #可能要加counter cache
  has_many :invite_msgs

  scope :find_inviting, -> {
    where(state: 'inviting')
  }
  # scope :order_by_invite_msg, ->{
  #   joins(:invite_msgs).order('invite_msgs.created_at DESC')
  # }

  def time_updated!
    self.updated_at = Time.now
    self.save
  end

  def send_accept_msg
    invite_msg = self.invite_msgs.create(content: "我已同意您的邀請，開始來解任務吧！ -- 系統訊息")
    invite_msg.user = self.invitee
    invite_msg.save
  end

  def send_decline_msg
    invite_msg = self.invite_msgs.create(content: "很抱歉，我無法跟你組隊（已拒絕任務） -- 系統訊息")
    invite_msg.user = self.invitee
    invite_msg.save
  end

  def send_cancel_msg(*msgs)
    if(msgs)
      msgs.each do |msg|
        invite_msg = self.invite_msgs.create(content: msg)
        invite_msg.user = self.user
        invite_msg.save
      end
    end

    invite_msg = self.invite_msgs.create(content: "很抱歉，我已取消這次邀請，有緣再見 -- 系統訊息")
    invite_msg.user = self.user
    invite_msg.save
  end

  def cancel!
    if self.state == 'inviting'
      self.state = 'cancel'
      self.save
    end
  end


  # for notification
  def recipient
    case self.state
    when 'inviting'
      self.invitee
    when 'cancel'
      self.invitee
    when 'accept'
      self.user
    when 'decline'
      self.user
    end

  end

  # for notification
  def create_notifications
    # 如果是藉由徵召的邀請函不要產生邀請訊息
    return if RecruitBoard.all.any? { |recruit_board| recruit_board.instance == self.instance}
    #Dirty object
    return if !self.id_previously_changed? && !self.state_previously_changed?
    actor =  ( recipient == self.user ? self.invitee : self.user )
    Notification.create(recipient: recipient, actor: actor,
        action: self.state, notifiable: self)
  end

  def test_callback
    binding.pry
  end

  private

  def setup_state!

    if self.state == 'accept'
      if !instance.is_member?(self.invitee)
        #join invitee into instance

        instance.members << invitee
        # binding.pry
        #要save才會呼叫after_commit
        instance.save
      end
    end
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :set_invitation, except: [:index, :sent_index]
  before_action :auth_invitee, only: [:accept, :decline]
  before_action :check_inviting, only: [:accept, :decline, :cancel]

  def index
    @received_invitations = Invitation.where(invitee_id: current_user).order(updated_at: :desc).page(params[:page]).per(8)
    #byebug.order_by_invite_msg
    @received_invitations_msgs_unread_count = current_user.recived_invite_msgs.joins(:invitation).where('invitations.invitee_id = ?', current_user.id).unread.count
    @sent_invitations_msgs_unread_count = current_user.recived_invite_msgs.joins(:invitation).where('invitations.user_id = ?', current_user.id).unread.count
  end

  def sent_index
    @sent_invitations = Invitation.where(user_id: current_user).order(updated_at: :desc).page(params[:page]).per(8)
    @received_invitations_msgs_unread_count = current_user.recived_invite_msgs.joins(:invitation).where('invitations.invitee_id = ?', current_user.id).unread.count
    @sent_invitations_msgs_unread_count = current_user.recived_invite_msgs.joins(:invitation).where('invitations.user_id = ?', current_user.id).unread.count
  end

  def show

    @inviter = @invitation.user                    #邀請者
    @invitee = @invitation.invitee                 #受邀者
    if current_user == @inviter || current_user == @invitee
      #只有邀請者或受邀者才可以瀏覽
      current_user.msg_read!(@invitation)
      @mission = @invitation.instance.mission
      @invite_msgs = @invitation.invite_msgs.order(id: :asc).includes(:user)
      if @invitation.state == 'inviting'
        @invite_msg = InviteMsg.new
      end
    else
      flash[:alert] = '::Invitation: 禁止瀏覽！'
      redirect_back(fallback_location: root_path)
    end

    respond_to do |format|
      format.html
      format.js
    end

  end

  def accept
    #受邀者可以接受邀請
    #before_aciton :auth_invitee
    #before_aciton :check_inviting
    # binding.pry
    @invitation.send_accept_msg
    @invitation.state = 'accept'
    @invitation.save
    # binding.pry
    flash[:notice] = '接受任務'
    redirect_to instance_path(@invitation.instance)
  end

  def decline
    # 受邀者可以拒絕邀請

    #before_aciton :auth_invitee
    #before_aciton :check_inviting
    @invitation.send_decline_msg
    @invitation.state = 'decline'
    @invitation.save
    flash[:notice] = '拒絕邀請'
    redirect_back(fallback_location: root_path)

  end

  def cancel
    #邀請者可以取消邀請
    #before_aciton :check_inviting

    #只有發起這個邀請的人可以取消邀請
    if current_user == @invitation.user

      @instance = @invitation.instance
      @invitation.send_cancel_msg
      @invitation.state= 'cancel'
      @invitation.save!
      @alert_msg = "取消邀請"

      @remaining_invitations_count = @instance.remaining_invitations_count
      @invitations = @instance.inviting_invitations.includes(:user)

      @filterrific = filterrific_user or return
      @candidates = @filterrific.find.can_be_invited(@instance).page(params[:page]).per(20)

      respond_to do |format|
        format.html { redirect_back(fallback_location: root_path) }
        format.js
      end

    else
      flash[:alert] = "操作失敗"
      redirect_back(fallback_location: root_path)
    end
  end

  def read_all_msg
    invitation = Invitation.find(params[:id])
    current_user.msg_read!(invitation)
  end

  private
  def set_invitation
    @invitation = Invitation.find(params[:id])
  end

  def auth_invitee
    #確認current_user是受邀者
    if current_user != @invitation.invitee
      flash[:alert] = '::invitation: 操作禁止'
      redirect_back(fallback_location: root_path)
    end
  end

  def check_inviting
    # 檢查邀請函狀態以及組隊狀態
    if @invitation.state != 'inviting' || @invitation.instance.state != 'teaming'
      flash[:alert] = 'Sorry，任務進行中或是邀請函失效！'
      redirect_back(fallback_location: root_path)
    end
  end

end

app/helpers/invitations_helper.rb
module InvitationsHelper

  def cross_invite_badges(invitation)

    if invitation.state == 'inviting'
      mission = invitation.instance.mission
      reverce_invitations = mission.invitations.where('invitations.user_id = ? AND invitations.invitee_id = ? AND invitations.state = ?', invitation.invitee, invitation.user ,'inviting')

      if reverce_invitations.present?
         content_tag(:span, '同任務互邀中' , class: "badge bg-green-dark ml-1")
      end
    end

  end

end

app/views/invitations/_invitation_msg.html.erb
<% if @invite_msgs %>
  <ul>
    <% @invite_msgs.each do |msg| %>
      <li><%= msg.user.name %> 說： <%= msg.content %></li>
    <% end %>
  </ul>
<% end %>

app/views/invitations/_invite_msg_board.html.erb
<% if msgs %>
  <% msgs.each do |msg| %>
    <%= render partial: 'invitations/invite_msg_show', locals: {msg: msg}%>
  <% end %>
<% end %>

app/views/invitations/_invite_msg_show.html.erb
<div class="col-12 m-0 ">
  <div class="table-responsive">
    <table class="table m-0">
      <tbody>
        <tr>
          <% if msg.user != current_user %>
            <td class="b0 wd-xs d-md-table-cell text-center">
              <%= gravatar_for(msg.user, "img-fluid rounded-circle img-thumbnail thumb48") %>
              <span><%= msg.user.name %></span>
            </td>
          <% end %>
          <td class="b0 <%= 'd-flex flex-column align-items-end' if msg.user == current_user %> ">
            <div class="w-50 bg-gray-darker px-3 py-2 rounded ">
              <span><%= msg.content %></span>
            </div>
            <span class="text-muted mt-1"><%= time_ago_in_words(msg.updated_at) + '前' %></span>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/invitations/_received_list.html.erb
<table class="table table-hover" id="received_list">
  <thead class="thead-dark">
    <tr>
      <th scope="col">任務名稱</th>
      <th scope="col">邀請人</th>
      <th scope="col">邀請狀態</th>
      <th scope="col">動作</th>
      <th scope="col">最後更新</th>
    </tr>
  </thead>
  <tbody>
    <% @received_invitations.each do |invitation| %>
      <tr>
        <td><%= link_to invitation.instance.mission.name, mission_path(invitation.instance.mission), remote: true%> <%= cross_invite_badges(invitation) %></td>
        <td><%= invitation.user.name %></td>
        <td><%= invitation.state %></td>
        <td>
          <% if invitation.state == 'inviting' %>
            <%= link_to '聊聊', invitation_path(invitation), remote: true, class: 'btn btn-primary' %>
          <% else %>
            <%= link_to '邀請紀錄', invitation_path(invitation), remote: true, class: 'btn btn-primary' %>
          <% end %>
          </td>
        <td><span style="display:none;"><%= invitation.updated_at %></span><%= time_ago_in_words(invitation.invite_msgs.last.updated_at) + '前更新' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/invitations/_sent_list.html.erb
<table class="table table-hover" id="sent_list">
  <thead class="thead-dark">
    <tr>
      <th scope="col">任務名稱</th>
      <th scope="col">受邀者</th>
      <th scope="col">邀請狀態</th>
      <th scope="col">動作</th>
      <th scope="col">最後更新</th>
    </tr>
  </thead>
  <tbody>
    <% @sent_invitations.each do |invitation| %>
      <tr>
        <td><%= link_to invitation.instance.mission.name, mission_path(invitation.instance.mission), remote: true%> <%= cross_invite_badges(invitation) %></td>
        <td><%= invitation.invitee.name %></td>
        <td><%= invitation.state %></td>
        <td>
          <% if invitation.state == 'inviting' %>
            <%= link_to '聊聊', invitation_path(invitation), remote: true, class: 'btn btn-primary' %>
          <% else %>
            <%= link_to '邀請紀錄', invitation_path(invitation), remote: true, class: 'btn btn-primary' %>
          <% end %>
          </td>
        <td><span style="display:none;"><%= invitation.updated_at %></span><%= time_ago_in_words(invitation.updated_at) + '前' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/invitations/_show.html.erb
<div class="modal-dialog modal-lg">
  <div class="modal-content">
    <div class="modal-header">
      <h4 class="modal-title"><%= @inviter.name %> 邀請 <%= @invitee.name %> 進行任務 (邀請函狀態：<%= @invitation.state %>)</h4>
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    </div>
    <div class="modal-body">
      <div class="container-fluid">
        <div class="row mb-4">
          <% if @inviter != current_user  %>
            <div class="col-md-6 mb-3">
              <h4>邀請者</h4>
              <%= render partial:'shared/user_card' , locals: {user: @inviter} %>
            </div>
          <% end %>
          <% if @invitee != current_user  %>
            <div class="col-md-6 mb-3">
              <h4>受邀者</h4>
              <%= render partial:'shared/user_card' , locals: {user: @invitee} %>
            </div>
          <% end %>
        </div>
        <div class="row mb-4 justify-content-center">
          <div class="col-12 ">
            <h4>邀請對話</h4>
          </div>
          <div class="col-12" id="invitation_msg" data-invitation-id = "<%= @invitation.id %>">
            <%= render partial:'invite_msg_board', locals: {msgs: @invite_msgs} %>
          </div>
        </div>
        <!-- 訊息留言 -->
        <% if @invitation.state == 'inviting' %>
          <%= simple_form_for @invite_msg, remote: true, url: invitation_invite_msgs_path(@invitation) do |f| %>
            <%= f.input :content, label: false, placeholder:'聊聊天吧...'%>
            <%= f.button :submit, '送出留言', class:"btn btn-primary submit" %>
          <%end%>
        <%end%>
        <!--===============================-->
      </div>
    </div>
    <% if @invitation.state == 'inviting' %>
      <div class="modal-footer">
        <div class="mx-auto">
          <% if current_user == @invitee %>
            <%= link_to '接受邀請', accept_invitation_path(@invitation), method: :post, class: "btn btn-primary"  %>
            <%= link_to '拒絕邀請', decline_invitation_path(@invitation), method: :post, data: {confirm: 'Are you sure?'}, class: "btn btn-danger"  %>
          <% else %>
            <%= link_to '取消邀請', cancel_invitation_path(@invitation), method: :post, data: {confirm: 'Are you sure?'}, class: "btn btn-danger" %>
          <% end %>
        </div>
      </div>
    <%end%>
  </div>
</div>

<script>
  startInviteMsgs();
  //註冊action cable channel
  //invite_msgs.js

  readInviteMsgs(<%= @invitation.id%>);
</script>

app/views/invitations/cancel.js.erb
$("#remaining_invitations").html("<%= @remaining_invitations_count %>");
$("#invited_list").html("<%= j(render partial: 'instances/invited_list') %>");
$("#filterrific_results").html("<%= j(render partial: 'instances/candidates_list', locals: { candidates: @candidates }) %>");
<%= render partial: "shared/notify_for_ajax" %>

app/views/invitations/index.html.erb
<aside class="aside-container">
  <%= render partial: "layouts/sidebar" %>
</aside>
<aside class="offsidebar d-none">
  <%= render partial: "layouts/right_sidebar" %>
</aside>
<section>
  <div class="section-container">
    <div class="content-wrapper">
      <div class="content-heading">
        <h3><%= title '任務邀請' %></h3>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-xl-3 col-lg-4">
            <div class="mb-boxes collapse">
              <div class="card card-default">
                <div class="card-body">
                  <ul class="nav nav-pills flex-column">
                    <li class="nav-item p-2 ">
                      <small class="text-muted">Invitation Boxs</small>
                    </li>
                    <li class="nav-item active invite_msg_nav">
                      <%= link_to invitations_path, class: "nav-link d-flex align-items-center" do%>
                        <em class="fa fa-fw fa-lg fa-inbox mr-2"></em>
                        <span>收到的邀請</span>
                        <%= content_tag :div, @received_invitations_msgs_unread_count, class: "ml-2 badge badge-danger" if @received_invitations_msgs_unread_count > 0 %>
                      <% end %>
                    </li>
                    <li class="nav-item invite_msg_nav">
                      <%= link_to sent_index_invitations_path , class: "nav-link d-flex align-items-center" do%>
                        <em class="fa fa-fw fa-lg fa-paper-plane-o mr-2"></em>
                        <span>寄出的邀請</span>
                        <%= content_tag :div, @sent_invitations_msgs_unread_count, class: "ml-2 badge badge-danger" if @sent_invitations_msgs_unread_count > 0 %>
                      <% end %>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div class="col-xl-9 col-lg-8">
            <div class="card card-default" id="invitaions_list">
              <div class="card-body bb">
                <%= %>
                <table class="table table-hover mb-mails">
                  <tbody>
                    <% @received_invitations.each do |invitation| %>
                    <tr>
                      <td>
                        <div class="d-flex">
                          <%= gravatar_for(invitation.user, "mb-mail-avatar mr-2") %>
                          <div class="mb-mail-meta ml-3">
                            <div class="mb-mail-subject">
                              <%= invitation.user.name %> 邀請你一起加入 <%= link_to invitation.instance.mission.name, mission_path(invitation.instance.mission), remote: true%> 任務 <%= cross_invite_badges(invitation) %> 
                                <%= content_tag :div, invitation.invite_msgs.unread_by(current_user).count, class: "ml-2 badge badge-danger",id: "unread_#{invitation.id}" if invitation.invite_msgs.unread_by(current_user).count > 0 %>
                            </div>
                            <div class="mb-mail-from">
                              <span class="badge bg-green">L<%= invitation.instance.mission.level %></span>
                              <span class="badge bg-info"> XP+ <%= invitation.instance.mission.xp %></span>
                              <%= render partial: 'shared/mission_tags', locals: {mission: invitation.instance.mission} %>
                            </div>
                            <div class="mb-mail-preview">
                              <%= time_ago_in_words(invitation.updated_at) + '前更新' %></div>
                          </div>
                          <div class="mb-mail-date ml-auto">
                            <% if invitation.state == 'inviting' %>
                                <%= link_to '回覆邀請', invitation_path(invitation), remote: true, class: 'btn btn-primary' %>
                              <% else %>
                                <%= link_to '對話紀錄', invitation_path(invitation), remote: true, class: 'btn bg-gray-darker' %>
                            <% end %>
                          </div>
                        </div>
                      </td>
                    </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
              <div class="card-body" >
                <%= paginate @received_invitations %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/invitations/sent_index.html.erb
<aside class="aside-container">
  <%= render partial: "layouts/sidebar" %>
</aside>
<aside class="offsidebar d-none">
  <%= render partial: "layouts/right_sidebar" %>
</aside>
<section>
  <div class="section-container">
    <div class="content-wrapper">
      <div class="content-heading">
        <h3><%= title '任務邀請' %></h3>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-xl-3 col-lg-4">
            <div class="mb-boxes collapse">
              <div class="card card-default">
                <div class="card-body">
                  <ul class="nav nav-pills flex-column">
                    <li class="nav-item p-2">
                      <small class="text-muted">Invitation Boxs</small>
                    </li>
                    <li class="nav-item invite_msg_nav">
                      <%= link_to invitations_path, class: "nav-link d-flex align-items-center" do%>
                        <em class="fa fa-fw fa-lg fa-inbox mr-2"></em>
                        <span>收到的邀請</span>
                        <%= content_tag :div, @received_invitations_msgs_unread_count, class: "ml-2 badge badge-danger" if @received_invitations_msgs_unread_count > 0 %>
                      <% end %>
                    </li>
                    <li class="nav-item active invite_msg_nav">
                      <%= link_to sent_index_invitations_path , class: "nav-link d-flex align-items-center" do%>
                        <em class="fa fa-fw fa-lg fa-paper-plane-o mr-2"></em>
                        <span>寄出的邀請</span>
                        <%= content_tag :div, @sent_invitations_msgs_unread_count, class: "ml-2 badge badge-danger" if @sent_invitations_msgs_unread_count > 0 %>
                      <% end %>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div class="col-xl-9 col-lg-8">
            <div class="card card-default">
              <div class="card-body bb" id="invitaions_list">
                <table class="table table-hover mb-mails">
                  <tbody>
                    <% @sent_invitations.each do |invitation| %>
                    <tr>
                      <td>
                        <div class="d-flex">
                          <%= gravatar_for(invitation.invitee, "mb-mail-avatar mr-2") %>
                          <div class="mb-mail-meta ml-3">
                            <div class="mb-mail-subject">
                              你邀請 <%= invitation.invitee.name %> 一起加入 <%= link_to invitation.instance.mission.name, mission_path(invitation.instance.mission), remote: true%> 任務 <%= cross_invite_badges(invitation) %>
                              <%= content_tag :div, invitation.invite_msgs.unread_by(current_user).count, class: "ml-2 badge badge-danger", id: "unread_#{invitation.id}" if invitation.invite_msgs.unread_by(current_user).count > 0 %>
                            </div>
                            <div class="mb-mail-from">
                              <span class="badge bg-green">L<%= invitation.instance.mission.level %></span>
                              <span class="badge bg-info"> XP+ <%= invitation.instance.mission.xp %></span>
                              <%= render partial: 'shared/mission_tags', locals: {mission: invitation.instance.mission} %>
                            </div>
                            <div class="mb-mail-preview">
                              <%= time_ago_in_words(invitation.updated_at) + '前更新' %>
                            </div>
                          </div>
                          <div class="mb-mail-date ml-auto">
                            <% if invitation.state == 'inviting' %>
                              <%= link_to '邀請對話', invitation_path(invitation), remote: true, class: 'btn btn-primary' %>
                              <% else %>
                                <%= link_to '對話紀錄', invitation_path(invitation), remote: true, class: 'btn bg-gray-darker' %>
                            <% end %>
                          </div>
                        </div>
                      </td>
                    </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
              <div class="card-body" >
                <%= paginate @sent_invitations %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/invitations/show.html.erb
<aside class="aside-container">
  <%= render partial: "layouts/sidebar" %>
</aside>
<aside class="offsidebar d-none">
  <%= render partial: "layouts/right_sidebar" %>
</aside>
<section>
  <div class="section-container">
    <div class="content-wrapper">
      <div class="content-heading">
        <h3><%= title @inviter.name+' 邀請 '+@invitee.name+' 進行任務 (邀請函狀態：'+@invitation.state+')' %></h3>
      </div>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-xl-8">
            <div class="card card-default">
              <div class="card-body bb">
                <% if @inviter != current_user  %>
                  <div class="col-md-6 mb-3">
                    <h4>邀請者</h4>
                    <%= render partial:'shared/user_card' , locals: {user: @inviter} %>
                  </div>
                <% end %>
                <% if @invitee != current_user  %>
                  <div class="col-md-6 mb-3">
                    <h4>受邀者</h4>
                    <%= render partial:'shared/user_card' , locals: {user: @invitee} %>
                  </div>
                <% end %>
              </div>
              <div class="card-body">
                <div class="col-12">
                  <h4>邀請對話</h4>
                </div>


                <div class="col-12" id="invitation_msg" data-invitation-id = "<%= @invitation.id %>" >
                  <%= render partial:'invite_msg_board', locals: {msgs: @invite_msgs} %>
                </div>
              </div>
              <div class="card-body bb">
                <div class="col-12">
                  <% if @invitation.state == 'inviting' %>
                    <%= simple_form_for @invite_msg, remote: true, url: invitation_invite_msgs_path(@invitation) do |f| %>
                      <%= f.input :content, label: false, placeholder:'聊聊天吧...'%>
                      <%= f.button :submit, '送出留言', class:"btn btn-primary submit" %>
                    <%end%>
                  <%end%>
                </div>
              </div>
              <% if @invitation.state == 'inviting' %>
                <div class="card-body text-center">
                  <% if current_user == @invitee %>
                    <%= link_to '接受邀請', accept_invitation_path(@invitation), method: :post, class: "btn btn-primary"  %>
                    <%= link_to '拒絕邀請', decline_invitation_path(@invitation), method: :post, data: {confirm: 'Are you sure?'}, class: "btn btn-danger"  %>
                  <% else %>
                    <%= link_to '取消邀請', cancel_invitation_path(@invitation), method: :post, data: {confirm: 'Are you sure?'}, class: "btn btn-danger" %>
                  <% end %>
                </div>
              <% end %>
            </div>
          </div>
          <div class="col-xl-4">
            <div class="card card-default">
              <div class="card-body bb">
                <div class="clearfix">
                  <div class="float-left">
                    <h4><%= @mission.name %></h4>
                    <%= render partial: 'shared/mission_tags', locals: {mission: @mission} %>
                  </div>
                  <div class="float-right">
                    <%= abort_button(@instance) %><%= cancel_button(@instance) %>
                  </div>
                </div>
              </div>
              <div class="card-body bb">
                <%= image_tag @mission.image_url, class: "rounded img-fluid my-3" %>
                <p><%= @mission.description %></p>
              </div>
              <table class="table">
                <tbody>
                  <tr>
                    <td>
                      <strong>Level</strong>
                    </td>
                    <td><%= @mission.level %></td>
                  </tr>
                  <tr>
                    <td>
                      <strong>任務人數</strong>
                    </td>
                    <td><%= @mission.participant_number %></td>
                  </tr>
                  <tr>
                    <td>
                      <strong>XP</strong>
                    </td>
                    <td><%= @mission.xp %></td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


<script>
    // 按enter可以直接送出
$('#new_invite_msg').keypress(function (e) {
        if(e.which == 13 && !e.shiftKey) {
            // e.form.submit();
            e.preventDefault()
            $('.submit').click();
            $('#invite_msg_content').val("");
        }
});


startInviteMsgs(); 
//註冊action cable channel
//invite_msgs.js
readInviteMsgs(<%= @invitation.id%>);
</script>

app/views/invitations/show.js.erb
$("#invitation_model").html("<%= j(render 'show') %>")
$("#invitation_model").modal("show")

  // 按enter可以直接送出
$('#new_invite_msg').keypress(function (e) {
        if(e.which == 13 && !e.shiftKey) {
            // e.form.submit();
            e.preventDefault();
            // $('#new_invite_msg').trigger('submit.rails');;
            //$('.submit').click();
            var elem = document.getElementById('new_invite_msg')
            Rails.fire(elem, 'submit');
            $('#invite_msg_content').val("");
        }
});
$('.submit').click(
  function(e){
    //$('#new_invite_msg').submit();
    e.preventDefault();
    var elem = document.getElementById('new_invite_msg')
    Rails.fire(elem, 'submit');
    $('#invite_msg_content').val("");
});