config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'instances/index'
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks", confirmations: "confirmations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  authenticated :user do
    root "missions#dashboard"
  end

  root 'public#landing'
  get 'story', :to => 'public#story'
  resources :announcements, only: [:show]
  resources :notifications do
    collection do
      post :mark_as_checked_all
      post :mark_as_read_all
    end
    member do
      post :mark_as_read
    end
  end
  resources :invitations, only: [:index, :show] do
    member do
      post :accept
      post :decline
      post :cancel
      post :read_all_msg
    end
    collection do
      get :sent_index
    end
    resources :invite_msgs, only: [:create]
  end
  resources :invite_msgs, only: [:show]
  resources :instances, only: [:show, :edit] do
    member do
      post :submit
      patch :submit  #任務完成，提交答案
      post :save
      post :cancel   #取消組隊
      post :abort    #放棄任務
    end

    collection do
      get :history
    end
    resources :instance_msgs, only: [:create]
  end

  resources :followships, only: [:create, :destroy]

  resources :missions, only: [:index, :show] do
    member do
      get :dashboard
      post :challenge
      get :select_user
      # POST challenge_mission_path 挑戰本任務
    end

    collection do
      get :teaming
    end
  end

  resources :reviews, only: [:index, :show] do
    member do
      patch :submit
    end
  end

  resources :users do
    member do
      post :invite
      get :repos
    end
  end

  namespace :admin do
    root "missions#index"
    resources :missions
    resources :instances, only: [:index]
    resources :announcements
  end

  resources :recruit_boards, only: [:index, :create, :destroy] do
    member do
      post :accept
    end
  end

  mount ActionCable.server => '/cable'

end

app/models/mission.rb
class Mission < ApplicationRecord
  mount_uploader :image, MissionImageUploader
  acts_as_taggable
  #mission.instances 可以列出所有本任務產生的副本
  has_many :instances
  has_many :invitations, through: :instances

  filterrific(
    default_filter_params: {
      sorted_by: 'level_asc',
    },
    available_filters: [
      :sorted_by,
      :with_tag
    ]
  )

  scope :sorted_by, lambda { |sort_option|
    # extract the sort direction from the param value.
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
    case sort_option.to_s
    when /^level_/
      order("missions.level #{ direction }")
    when /^xp_/
      order("missions.xp #{ direction }")
    when /^created_at_/
      order("missions.created_at #{ direction }")
    else
      raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
    end

  }

  scope :with_tag, lambda { |tag|
    Mission.tagged_with(tag)
  }

  def self.options_for_sorted_by
    [
      ['等級 低至高', 'level_asc'],
      ['等級 高至低', 'level_desc'],
      ['XP 低至高', 'xp_asc'],
      ['XP 高至低', 'xp_desc'],
      ['新任務優先', 'created_at_desc']
    ]
  end

  def self.options_for_tag
    tags = Mission.tag_counts_on(:tags).map {|tag| tag.name }
  end
end

app/controllers/admin/missions_controller.rb
class Admin::MissionsController < Admin::BaseController
  before_action :set_mission , only:[:show,:edit,:update,:destroy]

  def index
    @missions = Mission.all.order(:id)
  end

  def show 
    @mission = Mission.find(params[:id])
  end

  def new
    @mission = Mission.new
  end

  def create
    @mission = Mission.new
    @mission.name = mission_params[:name]
    @mission.level = mission_params[:level]
    @mission.description = mission_params[:description]
    @mission.participant_number = mission_params[:participant_number]
    @mission.invitation_number = mission_params[:invitation_number]
    @mission.image = mission_params[:image]
    @mission.xp = mission_params[:xp]
    new_tags = mission_params[:tag_list].split(",").reject { |c| c.empty? }
    @mission.tag_list.add(new_tags)

    if @mission.save
      flash[:notice] = "mission created!"
      redirect_to admin_mission_path(@mission)
    else
      flash[:alert] = "something wrong!"
      render :new
    end

  end

  def edit
  end

  def update
    update_params = mission_params
    @mission.tag_list = update_params[:tag_list]
    update_params.delete(:tag_list)
    if @mission.update(update_params)
      flash[:notice] = "mission updated!"
      redirect_to admin_mission_path(@mission)
    else
      render :edit
    end
  end

  def destroy
    @mission.destroy
    flash[:notice] = "mission delete"
    redirect_to admin_root_path
  end

  private

  def mission_params

    params.require(:mission).permit(:name,:level,:description,:participant_number,:invitation_number,:image, :tag_list, :xp)

  end

  def set_mission
    @mission = Mission.find(params[:id])
  end

end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController

  def dashboard
    @missions = Mission.all
    instances = Instance.all
    @announcements = Announcement.all.order(updated_at: :desc)
    @instance_complete_count = instances.find_complete.count
    @reviews = Review.all
    @users = User.all

    # 任務達成率
    @achievement_rate = ((@instance_complete_count.to_f / instances.count.to_f )*100).round

    # 探員龍虎榜
    @top_agents = @users.ordered_by_xp.limit(5)

    # 前線戰情匯報
    @followings_instance_activities = UserInstance.find_by_followings(current_user).limit(10).includes(:instance).includes(:user).includes(:mission).order('instances.updated_at DESC')

    # 熱門任務
    @hot_missions = @missions.order(instances_count: :desc).limit(4)
    # binding.pry
    # 推薦任務
    tag_sample = current_user.missions.tag_counts_on(:tags).sample
    @recommended_tag = tag_sample ? tag_sample[:name] : ''
    # binding.pry
    @recommended_missions = Mission.tagged_with(@recommended_tag).where('level <= ?', current_user.level).sample(4)

  end

  def index
    @filterrific = filterrific_mission or return
    @missions = @filterrific.find.page(params[:page]).per(20)
    respond_to do |format|
      format.html
      format.js
    end

  end

  def show
    @mission = Mission.find(params[:id])
    # 如果要看的任務為現在正在進行的任務會重新導向到副本頁面
    # current_instance = current_user.instances.select { |instance| instance.state == 'in_progress' }[0]
    # redirect_to current_instance if current_instance.mission_id == @mission.id
    respond_to do |format|
      format.html
      format.js
    end
  end

  def challenge
    #挑戰一個任務
    mission = Mission.find(params[:id])
    # binding.pry
    if current_user.take_mission?(mission) && current_user.not_in_banned_mission_list(mission)
      #如果user可以挑戰這個任務
      #產生一個新副本
      instance = current_user.instances.create(mission_id: params[:id])

      instance.xp = mission.xp
      #設定副本xp值
      #如果有特殊xp加乘 可以在這邊修改

      #current_user.save!
      instance.save!
      flash[:notice] = "挑戰任務成功"
      #redirect_back(fallback_location: root_path)
      redirect_to instance_path(instance)
    else
      flash[:alert] = "無法挑戰該任務"
      redirect_back(fallback_location: root_path)
    end
  end

  # 由使用者找任務組隊
  def teaming
    @user = User.find(params[:user_id])

    if @user != current_user && @user.available == true
      # 找出目前使用者跟欲組隊使用者之間最低的等級
      level = [@user.level, current_user.level].min
      # 撈出參與者大於一人且等級低於兩個使用者的任務
      @missions = Mission.order(level: :asc).where("participant_number > 1 and level <= ?", level).page(params[:page]).per(20)
      render 'index'
    else
      flash[:alert] = "無法執行本操作"
      redirect_back(fallback_location: root_path)
    end
  end

  def select_user
    # 先建立instance
    mission = Mission.find(params[:id])
    # 抓出要邀請的user
    user = User.find(params[:select_user])
    # 先建立instance
    # binding.pry
    if current_user.take_mission?(mission) && current_user.not_in_banned_mission_list(mission)
      instance = current_user.instances.create(mission_id: params[:id])
      instance.xp = mission.xp
      instance.save!
      # 直接對user發出邀請
      if instance.can_invite?(user)
      #產生邀請
      invitation = current_user.invitations.build(instance_id: instance.id, invitee_id: user.id)
      invitation.save
      @remaining_invitations_count = instance.remaining_invitations_count
      @invitations = instance.inviting_invitations.includes(:user)
      @filterrific = initialize_filterrific(
            User,
            params[:filterrific],
            select_options: {
              sorted_by: User.options_for_sorted_by,
              with_gender: ['male', 'female'],
              range_level: [['0-4', '0'], ['5-9', '5'], ['10-14', '10'], ['15-19', '15']],
            }
          ) or return
      @candidates = @filterrific.find.can_be_invited(instance).page(params[:page])

      flash[:notice] = "邀請#{user.name}挑戰任務成功"
      #redirect_back(fallback_location: root_path)
      redirect_to instance_path(instance)
      else
        #不能收invite
        flash[:alert] = '不能送出邀請'
        redirect_back(fallback_location: root_path)
      end
    else
      flash[:alert] = "無法挑戰該任務"
      redirect_back(fallback_location: root_path)
    end
  end
end

app/helpers/admin/missions_helper.rb
module Admin::MissionsHelper
end

app/helpers/missions_helper.rb
module MissionsHelper

  def challenge_button(mission,team_user = '')
    # 先確認此任務不是自己發起且正在進行或組隊中的任務
    if !current_user.not_in_banned_mission_list(mission)
        content_tag(:button, '挑戰任務中' , class: "btn btn-dark disabled")
    elsif team_user.present?
      link_to '送出任務邀約', select_user_mission_path(mission, select_user: @user), class: "btn bg-primary"
    elsif current_user.take_mission?(mission) #確認 user 可以挑戰任務

      if mission.participant_number < 2
        link_to "挑戰任務", challenge_mission_path(mission), method: :post, class: "btn bg-primary"
      else
        link_to "開始組隊", challenge_mission_path(mission), method: :post, class: "btn bg-primary"
      end
    else
      content_tag(:button, '等級不足' , class: "btn btn-dark disabled")
    end
  end

end

app/views/missions/_following_activity.html.erb
<div class="list-group-item">
  <div class="media">

  <% case user_instance.instance.state%>
  <% when 'teaming' %>

    <!-- 組隊中 -->
    <div class="align-self-start mr-2">
      <span class="fa-stack">
        <em class="fa fa-circle fa-stack-2x text-purple"></em>
        <em class="fa icon-refresh fa-stack-1x fa-inverse text-white"></em>
      </span>
    </div>
    <div class="media-body text-truncate">
       <p class="mb-1 text-purple"><a class=" m-0" href="#"><%=link_to user_instance.user.name, user_path(user_instance.user), remote: true ,class: 'text-purple m-0' %> 探員正準備挑戰【<%=link_to "#{user_instance.instance.mission.name} ", mission_path(user_instance.instance.mission), remote: true  ,class: 'text-purple m-0' %>】任務 </a>
       </p>
       <p class="m-0">
          <small> 組隊中
          </small>
       </p>
    </div>


  <% when 'cancel' %>
  <!-- 任務取消 -->
  <div class="align-self-start mr-2">
    <span class="fa-stack">
      <em class="fa fa-circle fa-stack-2x text-info"></em>
      <em class="fa fa-certificate fa-stack-1x fa-inverse text-white"></em>
    </span>
  </div>
  <div class="media-body text-truncate">
     <p class="mb-1 text-info"><a class=" m-0" href="#"><%=link_to user_instance.user.name, user_path(user_instance.user), remote: true ,class: 'text-info m-0' %> 探員已經取消【<%=link_to "#{user_instance.instance.mission.name} ", mission_path(user_instance.instance.mission), remote: true ,class: 'text-info m-0' %>】任務組隊</a>
     </p>
     <p class="m-0">
        <small>
          是不是找不到人呢？試著<%=link_to '主動邀約 '+user_instance.user.name, user_path(user_instance.user),class: 'text-info' %> 吧？
        </small>
     </p>
  </div>

  <% when 'in_progress' %>
  <!-- 任務進行中 -->
  <div class="align-self-start mr-2">
    <span class="fa-stack">
      <em class="fa fa-circle fa-stack-2x text-danger"></em>
      <em class="fa icon-fire fa-stack-1x fa-inverse text-white"></em>
    </span>
  </div>
  <div class="media-body text-truncate">
     <p class="mb-1 text-danger"><a class=" m-0" href="#"><%=link_to user_instance.user.name, user_path(user_instance.user), remote: true ,class: 'text-danger m-0' %> 探員正在執行【<%=link_to "#{user_instance.instance.mission.name} ", mission_path(user_instance.instance.mission), remote: true  ,class: 'text-danger m-0' %>】任務，與霸閣熱烈決鬥中 </a>
     </p>
     <p class="m-0">
        <small>祈禱任務順利進行吧
        </small>
     </p>
  </div>

  <% when 'complete' %>
  <!-- 任務完成 -->
  <div class="align-self-start mr-2">
    <span class="fa-stack">
      <em class="fa fa-circle fa-stack-2x text-success"></em>
      <em class="fa icon-check fa-stack-1x fa-inverse text-white"></em>
    </span>
  </div>
  <div class="media-body text-truncate">
     <p class="mb-1 text-success"><a class=" m-0" href="#"><%=link_to user_instance.user.name, user_path(user_instance.user), remote: true ,class: 'text-success m-0' %> 探員已經解了【<%=link_to "#{user_instance.instance.mission.name} ", mission_path(user_instance.instance.mission), remote: true  ,class: 'text-success m-0' %>】任務的霸閣 </a>
     </p>
     <p class="m-0 text-success-dark">
        <small><% user_instance.user.name%> 經驗值+ <%= user_instance.instance.xp %>
        </small>
     </p>
  </div>


  <% when 'abort' %>
  <!-- 任務中止 -->
  <div class="align-self-start mr-2">
    <span class="fa-stack">
      <em class="fa fa-circle fa-stack-2x text-warning"></em>
      <em class="fa icon-info fa-stack-1x fa-inverse text-white"></em>
    </span>
  </div>
  <div class="media-body text-truncate">
     <p class="mb-1 text-warning"><a class=" m-0" href="#"><%=link_to user_instance.user.name, user_path(user_instance.user), remote: true ,class: 'text-warning m-0' %> 探員參與的【<%=link_to "#{user_instance.instance.mission.name} ", mission_path(user_instance.instance.mission), remote: true  ,class: 'text-warning m-0' %>】任務已終止，宣告失敗。 </a>
     </p>
     <p class="m-0 text-warning-dark">
        <small> 這隻霸閣太刁鑽...
        </small>
     </p>
  </div>

  <%end%>


    <div class="ml-auto">
      <small class="text-muted ml-2"><%= time_ago_in_words user_instance.instance.updated_at %>前</small>
    </div>
  </div>
</div>

app/views/missions/_missions_list.html.erb
<div id="filterrific_results" >
  <div class="row">
    <div class="col-12 text-center my-2"><%= page_entries_info missions %></div>
    <% missions.each do |mission| %>
      <div class="col-sm-6 col-lg-4 col-xl-3 my-3">
        <%= render partial:"shared/mission_card" , locals: {mission: mission} %>
      </div>
    <% end %>
  </div>
  <%= paginate missions %>
</div>

app/views/missions/_show_mission.html.erb
<div class="modal-dialog modal-lg">
  <div class="modal-content">
    <div class="modal-header">
      <h4 class="modal-title"><%=@mission.name%></h4>
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    </div>
    <div class="modal-body">
      <div class="container-fluid">
        <div class="row mb-4">
          <div class="col-12">
            <%=image_tag @mission.image_url, class: "img-fluid rounded w-100" %>
          </div>
        </div>
        <div class="row mb-4">
          <div class="col-12">
            <ul>
              <li>任務名稱: <%=@mission.name%></li>
              <li>等級: <%= @mission.level%></li>
              <li>參加人數：<%= @mission.participant_number %></li>
              <li>XP經驗值獎勵：<%= @mission.xp %>點</li>
              <li>任務內容：<%= simple_format @mission.description %></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <% if request.referrer.try(:include?, missions_url) %>
      <div class="modal-footer">
        <div class="mx-auto">
          <%= challenge_button(@mission) %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/missions/dashboard.html.erb
<aside class="aside-container">
  <%= render partial: "layouts/sidebar" %>
</aside>
<aside class="offsidebar d-none">
  <%= render partial: "layouts/right_sidebar" %>
</aside>
<section>
  <div class="section-container">
    <div class="content-wrapper">
      <div class="content-heading">
        <h3><%= title '戰情中心' %></h3>
      </div>
      <div class="container dashboard">
        <!-- 全站監控版 -->
        <div class="row">
        <!-- 全站完成率 -->
          <div class="col-lg-3 mb-3">
            <div class="card">
                <div class="card-body">
                  <div class="text-center py-1">
                    <div class="easypie-chart easypie-chart-lg" data-easypiechart="" data-percent="<%= @achievement_rate %>" data-animate="{duration: 800, enabled:true}" data-bar-color="#23b7e5" data-track-color="rgba(200,200,200,0.4)" data-scale-color="false" data-line-width="10" data-line-cap="round" data-size="190">
                      <span><%= @achievement_rate %>%</span>
                    </div>
                  </div>
                </div>
              <div class="card-footer text-center text-muted">全員任務完成率</div>
            </div>
          </div>
          <div class="col-lg-9">
            <div class="row">
              <div class="col">
                <div class="card flex-row align-items-center align-items-stretch border-0">
                  <div class="col-4 d-flex align-items-center bg-danger-dark justify-content-center rounded-left">
                    <em class="fa fa-bug fa-5x"></em>
                  </div>
                  <div class="col-8 py-3 bg-danger rounded-right text-center">
                        <div class="display-4 mt-0 "><%=@instance_complete_count %></div>
                        <div class="text-uppercase">隻霸閣已被解決</div>
                  </div>
                </div>
              </div>
              <div class="col">
                <div class="card flex-row align-items-center align-items-stretch border-0">
                  <div class="col-4 d-flex align-items-center bg-green-dark justify-content-center rounded-left">
                  <em class="fa fa-user-secret fa-5x"></em>
                  </div>
                  <div class="col-8 py-3 bg-green rounded-right text-center" >
                    <div class="display-4 mt-0 "><%= @users.count %></div>
                    <div class="text-uppercase">位探員debug every night</div>
                  </div>
                </div>
              </div>
            </div>

            <div class="row mt-3">
              <div class="col">
                <div class="card flex-row align-items-center align-items-stretch border-0">
                  <div class="col-4 d-flex align-items-center bg-yellow-dark justify-content-center rounded-left">
                    <em class="icon-layers fa-5x"></em>
                  </div>
                  <div class="col-8 py-3 bg-yellow rounded-right text-center ">
                    <div class="display-4 mt-0 "><%= @missions.count %></div>
                    <div class="text-uppercase">個任務需要前往執行</div>
                  </div>
                </div>
              </div>
              <div class="col">
                <div class="card flex-row align-items-center align-items-stretch border-0">
                  <div class="col-4 d-flex align-items-center bg-info-dark justify-content-center rounded-left">
                    <em class="fa fa-comment-o fa-5x"></em>
                  </div>
                  <div class="col-8 py-3 bg-info rounded-right text-center">
                    <div class="display-4 mt-0 "><%= @reviews.count %></div>
                    <div class="text-uppercase">個任務評價</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="row mt-3">
          <div class="col-lg-8">
              <!-- ERM放送台 start -->
            <div class="card card-dark pt-2 announcement">
              <div class="card-header">
                <div class="card-title">ERM 放送台<span class="align-middle"><i class="fa fa-question-circle float-right " title="" data-container="body" data-trigger='hover' data-toggle="popover" data-placement="top" data-content="這裡是站方公告">
                </i></span></div>
              </div>
              <div class="card-body p-0" data-scrollable="">
                <div class="announcement">
                  <div class="list-group">
                    <% @announcements.each do |announcement| %>
                      <div class="list-group-item list-group-item-action border-0">
                        <div class="media">
                          <div data-toggle="tooltip" data-placement="bottom" title="<%= announcement.author.name %>">
                            <%= gravatar_for(announcement.author, "align-self-start mr-2 img-thumbnail rounded-circle thumb32") %>
                          </div>
                          <div class="media-body text-truncate">
                            <p class="mb-1">
                              <strong class="text-primary">
                                <span><%= link_to announcement.title, announcement_path(announcement), remote: true%></span>
                              </strong>
                            </p>
                          <p class="mb-1 text-sm"><%= announcement.content %></p>
                          </div>
                          <div class="ml-auto">
                            <small class="text-muted ml-2"><%=announcement.updated_at.strftime("%Y-%m-%d %H:%M")%></small>
                          </div>
                        </div>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
            <!-- ERM放送台 end -->

            <!-- 前線戰情彙報 start -->
            <div class="card card-default mt-3 activity-board">
              <div class="card-header">
                <div class="card-title">前線戰情彙報<span class="align-middle"><i class="fa fa-question-circle float-right " title="" data-container="body" data-trigger='hover' data-toggle="popover" data-placement="top" data-content="追蹤探員，來取得他的最新戰情彙報！">
                </i></span></div>
              </div>
              <div class="activity-board-content" data-scrollable="">
               <!-- START list group-->
              <div class="list-group">
                <!-- START list group item-->
                <% @followings_instance_activities.each do |user_instance| %>
                  <%=render partial:'following_activity',locals: {user_instance: user_instance} %>
                <%end%>
               </div>
               <!-- END list group-->
               <!-- START card footer-->
               </div>
               <div class="card-footer"><p class="text-right"><small class="text-muted text-right">前線資料傳送於<%= Time.now.strftime("%Y-%m-%d %H:%M")%></small></p>
               </div>
               <!-- END card-footer-->
            </div>

            <!-- 前線戰情會報 end -->

          </div>  <!-- col-lg-8 end -->

          <!-- 探員龍虎榜 start -->
          <div class="col">
            <div class="card">
              <div class="card-header">
                <div class="card-title">探員龍虎榜 <span class="align-middle"><i class="fa fa-question-circle float-right " title="" data-container="body" data-trigger='hover' data-toggle="popover" data-placement="top" data-content="XP值最高的探員">
                </i></span></div>
              </div>
            </div>
            <% @top_agents.each do |agent| %>
            <div class="card">
              <div class="card-body">
                <div class="row align-items-center">
                  <div class="col-5 text-center">
                    <%= image_tag gravatar_url(agent), class: 'img-thumbnail rounded-circle thumb80'%>
                  </div>
                  <div class="col-7">
                    <div class="text-right"><%= render partial: "shared/follow", locals: {user: agent} if agent != current_user %>
                    </div>
                    <div class="d-flex">
                      <div class="text-left">
                        <h3 class="mt-0"><%=link_to agent.name, user_path(agent), remote: true %></h3>
                        <p class="text-muted"><%= agent.xp %> XP / 已剷除 <%= agent.instances_completed_count %> 隻霸閣</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <%end%>
          </div>  <!-- col end -->
          <!-- 探員龍虎榜 end -->
        </div>  <!-- row end -->
      </div>

      <div class="content-heading mt-5">
        <h3>熱門任務</h3>
      </div>
      <div class="container dashboard">
        <div class="row mt-1">
          <% @hot_missions.each do |mission| %>
            <div class="col-sm-6 col-lg-4 col-xl-3 my-3">
              <%= render partial:"shared/mission_card" , locals: {mission: mission} %>
            </div>
          <% end %>
        </div>
      </div>
      <% unless @recommended_tag == '' %>
        <div class="content-heading mt-5">
          <h3>你曾經成功挑戰 <%= @recommended_tag %> 任務，推薦給你...</h3>
        </div>
        <div class="container dashboard">
          <div class="row mt-1">
            <% @recommended_missions.each do |mission| %>
              <div class="col-sm-6 col-lg-4 col-xl-3 my-3">
                <%= render partial:"shared/mission_card" , locals: {mission: mission} %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>


<script>
</script>

app/views/missions/index.html.erb
<aside class="aside-container">
  <%= render partial: "layouts/sidebar" %>
</aside>
<aside class="offsidebar d-none">
  <%= render partial: "layouts/right_sidebar" %>
</aside>
<section>
  <div class="section-container">
    <div class="content-wrapper">
      <div class="content-heading d-flex justify-content-between">

        <% if @user %>
          <div class=""><h3><%= title '邀請 '+@user.name+' 一起組隊' %></h3></div>
          <div ><span class="fa fa-question-circle  " title="" data-container="body" data-trigger='hover' data-toggle="popover" data-placement="top" data-content="可以直接挑選任務，對該探員送出組隊邀請！"> </span></div>
        <% else %>

          <div>
            <h3><%= title '任務牆' %></h3>
          </div>
          <div ><span class="fa fa-question-circle  " title="" data-container="body" data-trigger='hover' data-toggle="popover" data-placement="top" data-content="挑選一個任務挑戰：如果任務人數為2人，請邀請探員共同組隊挑戰，如果等級不足或者已經正在挑戰任務者，無法挑戰該任務。"> </span></div>
        <% end %>
      </div>
      <div class="container">
        <% if controller?('missions') && action?('index') %>
          <div class="row mb-0">
            <div class="col bg-inverse-light card mx-3">
              <div class="card-body">
                <%= form_for_filterrific @filterrific, remote: true do |f| %>
                  <div class="form-group row" >
                      <label class="col-12 col-sm-2">排序方式：</label>
                      <div class="col-12 col-sm-10 btn-group-toggle" data-toggle="buttons">
                        <% @filterrific.select_options[:sorted_by].each do |sorted_by| %>
                            <%= f.label sorted_by[0] ,class: "btn btn-dark mb-1 #{'active' if @filterrific.sorted_by == sorted_by[1]}" do %>
                              <%= f.radio_button :sorted_by, sorted_by[1] %> <%= sorted_by[0] %>
                            <% end %>
                        <% end %>
                      </div>
                    </div>
                    <div class="form-group row" >
                      <label class="col-12 col-sm-2">任務標籤：</label>
                      <div class="col-12 col-sm-10 btn-group-toggle" data-toggle="buttons">
                        <label class="btn btn-dark mb-1 <%= 'focus active' if @filterrific.with_tag.blank? %> ">
                          <%= f.radio_button :with_tag, '' %> All
                        </label>
                        <% @filterrific.select_options[:with_tag].each do |tag| %>
                            <%= f.label tag ,class: "btn btn-dark mb-1 #{'active' if @filterrific.with_tag == tag }" do %>
                              <%= f.radio_button :with_tag, tag %> <%= tag %>
                            <% end %>
                        <% end %>
                      </div>
                    </div>
                  <%= render_filterrific_spinner %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
        <%= render partial: 'missions_list', locals: { missions: @missions } %>
      </div>
    </div>
  </div>
</section>

app/views/missions/index.js.erb
$("#filterrific_results").html("<%= j(render partial: 'missions_list', locals: { missions: @missions }) %>");

app/views/missions/show.html.erb
<aside class="aside-container">
  <%= render partial: "layouts/sidebar" %>
</aside>
<aside class="offsidebar d-none">
  <%= render partial: "layouts/right_sidebar" %>
</aside>
<section>
  <div class="section-container">
    <div class="content-wrapper">
      <div class="content-heading">
        <h3><%= title @mission.name %></h3>
      </div>
      <div class="">
        <%=image_tag @mission.image_url %>
      </div>
      <div class="">
        <ul>
          <li>任務名稱: <%=@mission.name%></li>
          <li>等級: <%= @mission.level%></li>
          <li>參加人數：<%= @mission.participant_number %></li>
          <li>你還可發送 <%= @mission.invitation_number %> 張邀請</li>
          <li>任務內容：<%= simple_format @mission.description %></li>
        </ul>
      </div>
      <%= link_to "回首頁", root_path, class:"btn btn-secondary"%>
      <%= challenge_button(@mission) %>
    </div>
  </div>
</section>

app/views/missions/show.js.erb
$("#mission_model").html("<%= j(render 'show_mission') %>")
$("#mission_model").modal("show")